const actionTypes = {
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_DETAIL_PRODUCTS: "GET_DETAIL_PRODUCTS",
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    GET_USER: 'GET_USER',
    GET_DETAIL_USER: 'GET_DETAIL_USER',
    GET_ARTICLE: 'GET_ARTICLE',
    GET_DETAIL_ARTICLE: 'GET_DETAIL_ARTICLE',
    GET_ORDER: 'GET_ORDER',
    GET_ADD_ORDER: 'GET_ADD_ORDER',
    GET_CATEGORY_PRODUCT: 'GET_CATEGORY_PRODUCT',
    GET_CATEGORY_PRODUCT_DETAIL: 'GET_CATEGORY_PRODUCT_DETAIL',
    GET_CATEGORY_DISCOUNT: 'GET_CATEGORY_DISCOUNT',
    GET_CATEGORY_DISCOUNT_DETAIL: 'GET_CATEGORY_DISCOUNT_DETAIL',
    GET_CATEGORY_BANNER: 'GET_CATEGORY_BANNER',
    GET_CATEGORY_DETAIL_BANNER: 'GET_CATEGORY_DETAIL_BANNER',
    GET_ORDER_DETAIL: 'GET_ORDER_DETAIL',
}

export default actionTypes