const actionTypes = {
    RESET_MESSAGE: 'RESET_MESSAGE',

    GET_PRODUCTS: "GET_PRODUCTS",
    GET_DETAIL_PRODUCTS: "GET_DETAIL_PRODUCTS",

    
    GET_USER: 'GET_USER',
    GET_DETAIL_USER: 'GET_DETAIL_USER',


    GET_ARTICLE: 'GET_ARTICLE',
    GET_DETAIL_ARTICLE: 'GET_DETAIL_ARTICLE',


    GET_ORDER: 'GET_ORDER',
    GET_ADD_ORDER: 'GET_ADD_ORDER',
    GET_ORDER_DETAIL: 'GET_ORDER_DETAIL',


    GET_CATEGORY_PRODUCT: 'GET_CATEGORY_PRODUCT',
    GET_CATEGORY_PRODUCT_DETAIL: 'GET_CATEGORY_PRODUCT_DETAIL',
    CREATE_CATEGORY_PRODUCT: 'CREATE_CATEGORY_PRODUCT',
    UPDATE_CATEGORY_PRODUCT: 'UPDATE_CATEGORY_PRODUCT',


    GET_CATEGORY_DISCOUNT: 'GET_CATEGORY_DISCOUNT',
    GET_CATEGORY_DISCOUNT_DETAIL: 'GET_CATEGORY_DISCOUNT_DETAIL',


    GET_CATEGORY_BANNER: 'GET_CATEGORY_BANNER',
    GET_CATEGORY_DETAIL_BANNER: 'GET_CATEGORY_DETAIL_BANNER',


}

export default actionTypes