const actionTypes = {
    RESET_MESSAGE: 'RESET_MESSAGE',

    /** NOTIFICATION */
    GET_NOTIFICATION: 'GET_NOTIFICATION',
    GET_NOTIFICATION_ERR: 'GET_NOTIFICATION_ERR',
    ADD_NOTIFICATION: 'ADD_NOTIFICATION',
    ADD_NOTIFICATION_ERR : 'ADD_NOTIFICATION_ERR',
    DELETE_NOTIFICATION: 'DELETE_NOTIFICATION',
    DELETE_NOTIFICATION_ERR: 'DELETE_NOTIFICATION_ERR',
    EDIT_NOTIFICATION: 'EDIT_NOTIFICATION',
    EDIT_NOTIFICATION_ERR: 'EDIT_NOTIFICATION_ERR',

    /** WAREHOUSE */
    GET_WAREHOUSE: 'GET_WAREHOUSE',
    GET_WAREHOUSE_ERR: 'GET_WAREHOUSE_ERR',

    /** RECEIPT */
    GET_RECEIPT: 'GET_RECEIPT',
    GET_RECEIPT_ERR: 'GET_RECEIPT_ERR',
    ADD_RECEIPT: 'ADD_RECEIPT',
    ADD_RECEIPT_ERR: 'ADD_RECEIPT_ERR',
    GET_DETAIL_RECEIPT: 'GET_DETAIL_RECEIPT',
    UPDATE_RECEIPT: 'UPDATE_RECEIPT',
    GET_DETAIL_RECEIPT_ERR: 'GET_DETAIL_RECEIPT_ERR',
    UPDATE_RECEIPT_ERR: 'UPDATE_RECEIPT_ERR',
    DELETE_RECEIPT: 'DELETE_RECEIPT',
    DELETE_RECEIPT_ERR: 'DELETE_RECEIPT_ERR',

    /** COMMENT */
    GET_COMMENT: 'GET_COMMENT',
    GET_COMMENT_ERR: 'GET_COMMENT_ERR',
    FILTER_COMMENT: 'FILTER_COMMENT', 
    FILTER_COMMENT_ERR: 'FILTER_COMMENT_ERR', 


    /**  === AUTHEN === */
    LOGIN : 'LOGIN',
    LOGIN_FAIL: 'LOGIN_FAIL',


    /** === PRODUCT === */
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_DETAIL_PRODUCTS: "GET_DETAIL_PRODUCTS",
    ADD_PRODUCT_BY_ORDER: 'ADD_PRODUCT_BY_ORDER',
    CREATE_PRODUCT: 'CREATE_PRODUCT', 
    CREATE_PRODUCT_ERR: 'CREATE_PRODUCT_ERR', 
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    UPDATE_PRODUCT_ERR: 'UPDATE_PRODUCT_ERR',
    DELETE_PRODUCT_ERR: 'DELETE_PRODUCT_ERR',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    FILTER_PRODUCT: 'FILTER_PRODUCT',
    FILTER_PRODUCT_ERR: 'FILTER_PRODUCT_ERR',


    /** === USER === */
    GET_USER: 'GET_USER',
    CREATE_USER: 'CREATE_USER',
    CREATE_USER_ERROR: 'CREATE_USER_ERROR',
    GET_DETAIL_USER: 'GET_DETAIL_USER',
    UPDATE_USER: 'UPDATE_USER',
    FILTER_USER: 'FILTER_USER',
    FILTER_USER_ERR: 'FILTER_USER_ERR',
    DELETE_USER: 'DELETE_USER',
    DELETE_USER_ERR: 'DELETE_USER_ERR',


    /** === ARTICLE === */
    GET_ARTICLE: 'GET_ARTICLE',
    GET_ARTICLE_ERR: 'GET_ARTICLE_ERR',
    CREATE_ARTICLE: 'CREATE_ARTICLE',
    CREATE_ARTICLE_ERR: 'CREATE_ARTICLE_ERR',
    UPDATE_ARTICLE: 'UPDATE_ARTICLE',
    UPDATE_ARTICLE_ERR: 'UPDATE_ARTICLE_ERR',
    GET_DETAIL_ARTICLE: 'GET_DETAIL_ARTICLE',
    FILTER_ARTICLE: 'FILTER_ARTICLE',
    FILTER_ARTICLE_ERR: 'FILTER_ARTICLE_ERR',
    DELETE_ARTICLE: 'DELETE_ARTICLE',
    DELETE_ARTICLE_ERR: 'DELETE_ARTICLE_ERR',


    /** === ORDER === */
    GET_ORDER: 'GET_ORDER',
    GET_ADD_ORDER: 'GET_ADD_ORDER',
    GET_ORDER_DETAIL: 'GET_ORDER_DETAIL',
    UPDATE_ORDER: 'UPDATE_ORDER',
    ADD_ORDER: 'ADD_ORDER',
    FILTER_ORDER: 'FILTER_ORDER',
    DELETE_ORDER: 'DELETE_ORDER',

    /** === CATEGORY PRODUCT === */
    GET_CATEGORY_PRODUCT: 'GET_CATEGORY_PRODUCT',
    GET_CATEGORY_PRODUCT_DETAIL: 'GET_CATEGORY_PRODUCT_DETAIL',
    CREATE_CATEGORY_PRODUCT: 'CREATE_CATEGORY_PRODUCT',
    UPDATE_CATEGORY_PRODUCT: 'UPDATE_CATEGORY_PRODUCT',
    DELETE_CATEGORY_PRODUCT: 'DELETE_CATEGORY_PRODUCT',


    /** === CATEGORY DISCOUNT === */
    GET_CATEGORY_DISCOUNT: 'GET_CATEGORY_DISCOUNT',
    GET_CATEGORY_DISCOUNT_DETAIL: 'GET_CATEGORY_DISCOUNT_DETAIL',
    CREATE_DISCOUNT: 'CREATE_DISCOUNT',
    CREATE_DISCOUNT_ERR: 'CREATE_DISCOUNT_ERR',
    UPDATE_DISCOUNT: 'UPDATE_DISCOUNT',
    UPDATE_DISCOUNT_ERR: 'UPDATE_DISCOUNT_ERR',
    FILTER_DISCOUNT: 'FILTER_DISCOUNT',
    FILTER_DISCOUNT_ERR: 'FILTER_DISCOUNT_ERR',


    /** === CATEGORY BANNER === */
    GET_CATEGORY_BANNER: 'GET_CATEGORY_BANNER',
    GET_CATEGORY_DETAIL_BANNER: 'GET_CATEGORY_DETAIL_BANNER',
    UPDATE_BANNER: 'UPDATE_BANNER',
    UPDATE_BANNER_ERR: 'UPDATE_BANNER_ERR',
    CREATE_BANNER: 'CREATE_BANNER',
    CREATE_BANNER_ERR: 'CREATE_BANNER_ERR',
    FILTER_BANNER: 'FILTER_BANNER',
    FILTER_BANNER_ERR: 'FILTER_BANNER_ERR',

    /** === CATEGORY VIDEO */
    GET_CATEGORY_VIDEO: 'GET_CATEGORY_VIDEO',
    GET_CATEGORY_VIDEO_DETAIL: 'GET_CATEGORY_VIDEO_DETAIL',
    CREATE_CATEGORY_VIDEO: 'CREATE_CATEGORY_VIDEO',
    UPDATE_CATEGORY_VIDEO: 'UPDATE_CATEGORY_VIDEO',
    FILTER_VIDEO: 'FILTER_VIDEO',
    FILTER_VIDEO_ERR: 'FILTER_VIDEO_ERR',

    /** SUPPLIER */
    GET_SUPPLIER: 'GET_SUPPLIER',
    ADD_SUPPLIER: 'ADD_SUPPLIER',
    ADD_SUPPLIER_ERR: 'ADD_SUPPLIER_ERR',
    GET_DETAIL_SUPPLIER: 'GET_DETAIL_SUPPLIER',
    GET_DETAIL_SUPPLIER_ERR: 'GET_DETAIL_SUPPLIER_ERR',
    UPDATE_SUPPLIER: 'UPDATE_SUPPLIER',
    UPDATE_SUPPLIER_ERR: 'UPDATE_SUPPLIER_ERR',
    GET_PRODUCT_BY_SUPPLIER: 'GET_PRODUCT_BY_SUPPLIER',
    GET_PRODUCT_BY_SUPPLIER_ERR: 'GET_PRODUCT_BY_SUPPLIER_ERR',
    DELETE_SUPPLIER: 'DELETE_SUPPLIER',
    DELETE_SUPPLIER_ERR: 'DELETE_SUPPLIER_ERR',
    FILTER_SUPPLIER: 'FILTER_SUPPLIER',
    FILTER_SUPPLIER_ERR: 'FILTER_SUPPLIER_ERR',
    GET_SUPPLIER_ERR: 'GET_SUPPLIER_ERR',

}

export default actionTypes